### ISSUE TITLE
Upload all previously submitted questions with all submissions

### ISSUE THREAD

**Issue by ab-dauletkhan** [arunbhardwaj/LeetHub-2.0#38]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arunbhardwaj** [comment]
Hi @ab-dauletkhan, a feature like this can be risky and may get users rate limited by GitHub (and maybe even LeetCode) for so many requests depending on how many submissions the user has made. Also since multiple previous submissions would necessitate automatic tagging (or manual tagging for each file), it seems like it would have limited benefit as well. Although, one use case that I can see beneficial from this is to have different types of solutions with varying implementation methods and so I may look into that. For now, as a workaround please check out the manual submission feature in `v2.0.5` by going to any submission page for any problem and you should see a button in the submission/accepted window.
