### ISSUE TITLE
Extension stopped working with new site layout

### ISSUE THREAD

**Issue by elliotvhill** [arunbhardwaj/LeetHub-2.0#70]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
The extension does not log submissions since LeetCode updated their UI.

**To Reproduce**
An example of the new URL path is https://leetcode.com/problems/counter/description/ where the old path was https://leetcode.com/problems/counter/

**Expected behavior**
Extension should update the count of problems solved.

**Screenshots**
n/a

**Additional context**
When reverting to the old LeetCode UI, the extension starts logging submissions again.

**Comment by whynesspower** [comment]
@arunbhardwaj @elliotvhill Is there someone working on this issue? I suspect it has been more than three weeks since the extension has been dead.

**Comment by arunbhardwaj** [comment]
Fixed in the most recent update to the extension! Of note, LeetCode has separated their frontend problem numbers from their backend id numbers, which the extension uses for submission. For this particular problem, please verify in your GitHub under "2732" that the problem was published successfully.
