### ISSUE TITLE
Leetcode solutions not getting committed to the repository!!

### ISSUE THREAD

**Issue by Saani765** [arunbhardwaj/LeetHub-2.0#9]
I have authorized my Github with the extension but still the solutions are not getting fully committed .what I mean is that 3 solutions were added to my linked repository without an issue but after that my accepted solutions are not getting added to my repo. Can anyone help me out with this please?

**Comment by zsarge** [comment]
I'm experiencing this as well. If I had to guess, one reason could be that submissions to GitHub are triggered by [an event listener](https://github.com/arunbhardwaj/LeetHub-2.0/blob/1fbacf0e622e34cf40b214714766573a1661eb44/scripts/leetcode.js#L1021-L1029), added by a timeout, so when the site takes >2 seconds to load, your submissions trigger nothing.

One idea for a feature would be to add a manual "force submit" button under the pop up from the extension icon, but a better fix is to ensure that the event listener is always properly attached to the button.

Besides the StackOverflow answer in the comments of the code, I'm also considering adding an event listener for [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event), but I have no idea if it's triggered at an appropriate time, due to LeetCode's progressive loading of DOM elements.

If I have time to set up extension development, I'll submit a PR to resolve this issue. Or not idk. :skull:

**Comment by master-of-none** [comment]
The solutions are not getting committed, after the leetocode update today.

**Comment by 22arun11** [comment]
> The solutions are not getting committed, after the leetocode update today.

Yes even im facing the same problem but it works when i change it to the old UI could you guys please look into it

**Comment by master-of-none** [comment]
Thank you @arunbhardwaj for fixing this 🥳

**Comment by Saani765** [comment]
Thankyou sir for the response :)
